In [2]:
# creaing arrays through lists
import numpy as np
arra1 = np.array([1, 4, 1234, 412])
print(arra1, type(arra1))



[   1    4 1234  412] <class 'numpy.ndarray'>


In [3]:
# creating 2d arrays 
arry1 = np.array([[1, 4, 23],[5,23,234],[5,67,24]])
print(arry1, arry1.shape) 


[[  1   4  23]
 [  5  23 234]
 [  5  67  24]] (3, 3)


In [4]:
# creating arrays from scratch
arr = np.zeros((2,4)) # prefilled
print(arr)
arr1 = np.ones((4,)) # prefilled
print(arr1)
arr2 = np.full((3,4), 18) # prefillled with certain value
print (arr2)
arr3 = np.eye(2) # identity matrix
print(arr3)
arr4 = np.arange(0,11,3) # range elements
print(arr4) 
Array6= np.linspace(1, 500, 6) # Evenly spaced arrays
print(Array6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1.]
[[18 18 18 18]
 [18 18 18 18]
 [18 18 18 18]]
[[1. 0.]
 [0. 1.]]
[0 3 6 9]
[  1.  100.8 200.6 300.4 400.2 500. ]


In [5]:
# Operations on arrays

In [29]:
array12 = np.array([[1,23,42],[3,2,53]])
print(array12, array12.shape)
array21 = array12.reshape(3,2)   # reshaping the array
print(array21)  
array32 = array21.flatten()     # convert the 2d array into 1D
print(array32)
print(array12[0][2])

# fancy indexing
ind = [1,2]
print(arr2[ind])

# bolean indexing

print(arry1[arry1 >100])

# slicing

print(arry1[1:2])

# Axes in multidimmentional array
array2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array2D)
print(np.sum(array2D))    # sum of all the values of the array

sum_col = print(np.sum(array2D, axis = 0))
sum_row = print(np.sum(array2D, axis = 1))
print(array2D[0:2, 1:2])

# 3D array

Array3D = np.array([[[1,2,3],[4,5,6],[7,8,9]], [[10,11,12],[13,14,15],[16,17,18]]])
print(Array3D)
print(Array3D[:, 0, :])  # First rows of Both layers
print(Array3D[:, :, 0])  # First coloumns of Both layers

Array3D[:,0,:] = 99
print (Array3D)

# Vectorization and Broadcasting

array2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print( array2D ** 3)  # Vectorization

# print(array2D + arr2) perands could not be broadcast together with shapes (3,3) (3,4)

print(array2D + arry1)

mean = np.mean(array2D)
std_dev = np.std(array2D)
Normalized_array = (array2D-mean)/std_dev

print(Normalized_array)
print(mean)
print(std_dev)









 


[[ 1 23 42]
 [ 3  2 53]] (2, 3)
[[ 1 23]
 [42  3]
 [ 2 53]]
[ 1 23 42  3  2 53]
42
[[18 18 18 18]
 [18 18 18 18]]
[234]
[[  5  23 234]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
[[ 1  2  3]
 [10 11 12]]
[[ 1  4  7]
 [10 13 16]]
[[[99 99 99]
  [ 4  5  6]
  [ 7  8  9]]

 [[99 99 99]
  [13 14 15]
  [16 17 18]]]
[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]
[[  2   6  26]
 [  9  28 240]
 [ 12  75  33]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
5.0
2.581988897471611
